status_camera:
  resolution:
    x: 320
    y: 240
  rotation:
    degrees: 180

mqtt:
  ip_server: "192.168.1.15"

known_people:

- Vincenzo:
    file: "/home/pi/GassistPi/recognition/vincenzo.jpg"
    topic: "mqtt/test"

