#Config file for declaring custom actions'parameters. The parameters have been listed here in alphabetical order (A-Z).


#API Key for YouTube Search Engine
Google_cloud_api_key: "ENTER-YOUR-GOOGLE-CLOUD-API-KEY-HERE"


#KODI custom declarations change IP, music directory and video directory according to your device
Kodi:
  Kodi_Control: 'Disabled'
  ip: 192.168.88.226
  port: 8080
  username: kodi
  password: kodi
  musicdirectory: '/home/osmc/Music/'
  videodirectory: '/home/osmc/Movies/'
  windowcmd:
    - Home
    - Settings
    - Weather
    - Videos
    - Music
    - Player
  window:
    - home
    - settings
    - weather
    - videos
    - music
    - playercontrols


#Text to speech conversation
TextToSpeech:
  Voice_Gender: 'Female'

#Custom wakeword On/Off.
#To enable custom wakeword, change status to Enabled and restart the assistant.
Wakewords:
  Custom_wakeword_models:
    - '/home/pi/GassistPi/src/resources/kodi.pmdl'
